// @test error

fn main()
{
	3 = 4;
	return 4;
}