// @test error

fn main() : int
{
	int x = 4 +