// @test error

fn main()
{
	int x = 4 +