// @test error

fn main() : int
{
	while (true)
}